# Generated by Django 4.1.7 on 2023-03-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='img',
            new_name='image',
        ),
    ]
