# Generated by Django 4.1.7 on 2023-03-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0003_rename_body_information_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='information',
            name='phase',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Complete', 'Complete')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='convoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convoys.convoy'),
        ),
    ]
