# Generated by Django 4.1.7 on 2023-03-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0004_convoy_information_phase_information_convoy'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvoyCategoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('safety', 'safety'), ('vehicle-info', 'vehicle-info'), ('convoy-checklist', 'convoy-checklist')], max_length=20, null=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='convoy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.AddField(
            model_name='convoycategoryrecord',
            name='convoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='convoys.convoy'),
        ),
    ]
