# Generated by Django 4.1.7 on 2023-03-17 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0005_convoycategoryrecord_convoy_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convoycategoryrecord',
            name='convoy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='convoys.convoy'),
        ),
    ]
