# Generated by Django 4.1.7 on 2023-03-18 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('convoys', '0006_alter_convoycategoryrecord_convoy'),
    ]

    operations = [
        migrations.AddField(
            model_name='convoycategoryrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
