# Generated by Django 4.1.7 on 2023-03-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0007_convoycategoryrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convoycategoryrecord',
            name='category',
            field=models.CharField(blank=True, choices=[('Safety', 'Safety'), ('Vehicle Info', 'Vehicle Info'), ('Convoy Checklist', 'Convoy Checklist')], max_length=20, null=True),
        ),
    ]
