# Generated by Django 4.1.7 on 2023-03-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convoys', '0009_convoy_destination_convoy_orign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='convoy',
            old_name='orign',
            new_name='origin',
        ),
    ]
